version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    container_name: meu_postgres
    environment:
      POSTGRES_DB: newdatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    container_name: meu_adminer
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  picpay-finances:
    build:
      context: .
      dockerfile: Dockerfile
    image: picpay-finances
    container_name: picpay_finances_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/newdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - '8081:8080'

volumes:
  postgres_data: